# Generated by Django 4.0.5 on 2022-06-29 22:22

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_comment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('In Stock', 'In Stock'), ('Out Of Stock', 'Out Of Stock')], default='In Stock', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Hot', 'Hot'), ('Sale', 'Sale')], default='New', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='small_product_details',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
