# Generated by Django 3.2.14 on 2022-07-10 09:48

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='name1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='setting',
            name='name2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='setting',
            name='name3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='setting',
            name='position1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='setting',
            name='position2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='setting',
            name='position3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='setting',
            name='slide1',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='setting',
            name='slide2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='setting',
            name='slide3',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='setting',
            name='slidecomment1',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='setting',
            name='slidecomment2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='setting',
            name='slidecomment3',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='setting',
            name='phone',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AlterField(
            model_name='setting',
            name='whatsappcontact',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
