# Generated by Django 4.0.5 on 2022-06-25 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_setting_facebook_alter_setting_instagram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='address',
        ),
    ]
