# Generated by Django 4.0.5 on 2022-06-25 10:55

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_setting_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='contactcomment',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=100),
        ),
    ]
