# Generated by Django 4.0.5 on 2022-06-25 10:58

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_setting_contactcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='contactcomment',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=200),
        ),
    ]
