# Generated by Django 4.0.5 on 2022-06-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_setting_contactcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='youtube',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
