# Generated by Django 4.0.5 on 2022-06-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_setting_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='whaatsappcontact',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
