# Generated by Django 4.0.5 on 2022-06-25 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_whaatsappcontact_setting_whatsappcontact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactFormMessage',
            new_name='ContactMessage',
        ),
    ]
